
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: skragdemoqueue
  namespace: sk-rag-demo
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString # Required
    secretKeyRef:
      name: ServiceBusConnectionString
      key:  ServiceBusConnectionString
auth:
  secretStore: skragdemoakv