apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: skcodemotion2023akv
  namespace: codemotion2023
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: kv-skcodemotion2023
  - name: azureClientId
    value: "d53cfbc6-6de7-43a1-a247-4bff27284a40"