apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "knowledgebasefrontendchart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: skcodemotion2023-knowledgebase.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ include "knowledgebasefrontendchart.fullname" . }}
            port:
              number: 80
        pathType: Exact