{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowledgebasefrontendchart.fullname" . }}
  labels:
    {{- include "knowledgebasefrontendchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "knowledgebasefrontendchart.selectorLabels" . | nindent 4 }}
{{- end }}
